- hosts: sync_gateways

  vars:
    sync_gateway_config_file_name:

  remote_user: root

  tasks:
  - name: stop sync_gateway
    service: name=sync_gateway state=stopped
  - name: clear logs
    shell: rm -rf /home/sync_gateway/logs/*
  - name: using config
    debug: msg={{ sync_gateway_config_file_name }}
  - name: install sync gateway service
    shell: ./sync_gateway_service_install.sh --sgpath=/home/sync_gateway/sync_gateway --cfgpath=/home/sync_gateway/config/{{ sync_gateway_config_file_name }} chdir=/root/sync_gateway/service
  - name: wait until sync gateway to listen on port
    wait_for: port=4985 delay=1 timeout=30
